# Generated by Django 4.2.16 on 2024-11-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourist_apps', '0002_logintable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('no_of_people', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resort_name', models.CharField(max_length=100)),
            ],
        ),
    ]
