# Generated by Django 4.2.16 on 2024-11-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourist_apps', '0005_rename_new_cartitem_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
