# Generated by Django 4.2.16 on 2024-11-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourist_apps', '0006_booking_booking_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='persons',
            new_name='no_of_people',
        ),
    ]
