# Generated by Django 4.2.16 on 2024-11-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourist_apps', '0007_rename_persons_cartitem_no_of_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rate',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('standard', 'Standard Booking'), ('deluxe', 'Deluxe Booking'), ('suite', 'Suite Booking')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
