# Generated by Django 4.2.16 on 2024-11-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourist_apps', '0008_remove_booking_rate_booking_booking_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_total',
        ),
    ]
